# Generated by Django 5.1.7 on 2025-04-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_vehicle_options'),
        ('spring_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsetup',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='cars.vehicle'),
        ),
        migrations.AlterField(
            model_name='springcalculation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle'),
        ),
        migrations.AlterField(
            model_name='gearcalculation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
