# Generated by Django 5.1.7 on 2025-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lever_ratio_front', models.FloatField(blank=True, help_text='Front suspension lever ratio', null=True)),
                ('lever_ratio_rear', models.FloatField(blank=True, help_text='Rear suspension lever ratio', null=True)),
            ],
        ),
    ]
