# Generated by Django 5.1.7 on 2025-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Car'), ('RACE', 'Race Car'), ('GR4', 'Gr.4 Race Car'), ('VGT', 'Vision GT'), ('FAN', 'Fantasy/Concept')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('4WD', 'Four-Wheel Drive'), ('FF', 'Front-Engine Front-Wheel Drive'), ('FR', 'Front-Engine Rear-Wheel Drive'), ('MR', 'Mid-Engine Rear-Wheel Drive'), ('RR', 'Rear-Engine Rear-Wheel Drive')], max_length=3, null=True),
        ),
    ]
