# Generated by Django 5.1.7 on 2025-04-15 06:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehicle_car_type_vehicle_drivetrain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='base_power',
            field=models.IntegerField(blank=True, default=300, help_text='Base power in HP', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='base_pp',
            field=models.FloatField(blank=True, help_text='Base Performance Points', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='base_weight',
            field=models.IntegerField(default=1400, help_text='Base weight in kg', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('ROAD', 'Road Car'), ('GR4', 'Group 4 Racing'), ('GR3', 'Group 3 Racing'), ('RACE', 'Race Car'), ('VGT', 'Vision Gran Turismo'), ('FAN', 'Fantasy')], default='ROAD', max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(choices=[('4WD', '4-Wheel Drive'), ('FF', 'Front Engine, Front Wheel Drive'), ('FR', 'Front Engine, Rear Wheel Drive'), ('MR', 'Mid Engine, Rear Wheel Drive'), ('RR', 'Rear Engine, Rear Wheel Drive')], default='FR', max_length=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lever_ratio_front',
            field=models.FloatField(default=1.0, help_text='Front suspension lever ratio', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lever_ratio_rear',
            field=models.FloatField(default=1.0, help_text='Rear suspension lever ratio', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name'], name='cars_vehicl_name_b3bbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make'], name='cars_vehicl_make_66c748_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['drivetrain'], name='cars_vehicl_drivetr_128e59_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['car_type'], name='cars_vehicl_car_typ_40948e_idx'),
        ),
    ]
