# Generated by Django 5.1.7 on 2025-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name'], 'verbose_name': 'name', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='cars_vehicl_vehicle_0eabf9_idx',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name'], name='cars_vehicl_name_b3bbaf_idx'),
        ),
    ]
