# Generated by Django 5.1.7 on 2025-04-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
