# Generated by Django 5.1.7 on 2025-03-15 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_vehicle_car_type_vehicle_drivetrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_weight_distribution', models.FloatField(default=0.5, help_text='Front weight distribution (0-1)')),
                ('front_ride_height', models.IntegerField(default=100, help_text='Front ride height in mm')),
                ('rear_ride_height', models.IntegerField(default=100, help_text='Rear ride height in mm')),
                ('front_downforce', models.IntegerField(default=0, help_text='Front downforce')),
                ('rear_downforce', models.IntegerField(default=0, help_text='Rear downforce')),
                ('stiffness_multiplier', models.FloatField(default=1.0, help_text='Stiffness multiplier')),
                ('spring_frequency_offset', models.IntegerField(default=0, help_text='Spring frequency offset (-5 to 6)')),
                ('front_spring_rate', models.FloatField(blank=True, help_text='Calculated front spring rate (N/mm)', null=True)),
                ('rear_spring_rate', models.FloatField(blank=True, help_text='Calculated rear spring rate (N/mm)', null=True)),
                ('front_spring_frequency', models.FloatField(blank=True, help_text='Front spring frequency (Hz)', null=True)),
                ('rear_spring_frequency', models.FloatField(blank=True, help_text='Rear spring frequency (Hz)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle')),
            ],
        ),
    ]
