# Generated by Django 5.1.7 on 2025-03-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='springcalculation',
            name='vehicle_weight',
            field=models.IntegerField(default=0, help_text='Vehicle weight in kg'),
        ),
    ]
