# Generated by Django 5.1.7 on 2025-03-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0002_springcalculation_vehicle_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireSizeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(help_text='Vehicle speed in km/h')),
                ('rpm', models.IntegerField(help_text='Engine RPM')),
                ('gear_ratio', models.FloatField(help_text='Current gear ratio')),
                ('final_drive', models.FloatField(help_text='Final drive ratio')),
                ('tire_size', models.FloatField(blank=True, help_text='Calculated tire size in inches', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
