# Generated by Django 5.1.7 on 2025-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0005_remove_springcalculation_front_spring_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='springcalculation',
            name='front_spring_rate',
            field=models.FloatField(blank=True, help_text='Calculated front spring rate (N/mm)', null=True),
        ),
        migrations.AddField(
            model_name='springcalculation',
            name='rear_spring_rate',
            field=models.FloatField(blank=True, help_text='Calculated rear spring rate (N/mm)', null=True),
        ),
    ]
