# Generated by Django 5.1.7 on 2025-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0006_springcalculation_front_spring_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='springcalculation',
            name='arb_stiffness_multiplier',
            field=models.FloatField(default=1.0, help_text='ARB Stiffness multiplier'),
        ),
        migrations.AddField(
            model_name='springcalculation',
            name='front_tires',
            field=models.CharField(blank=True, help_text='Front tire type', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='springcalculation',
            name='performance_points',
            field=models.IntegerField(blank=True, help_text='Performance Points (PP)', null=True),
        ),
        migrations.AddField(
            model_name='springcalculation',
            name='rear_tires',
            field=models.CharField(blank=True, help_text='Rear tire type', max_length=30, null=True),
        ),
    ]
