# Generated by Django 5.1.7 on 2025-03-22 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0008_remove_springcalculation_rotational_g_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearratiocalculation',
            name='track',
        ),
        migrations.RemoveField(
            model_name='gearratiocalculation',
            name='traction_control_value',
        ),
        migrations.RemoveField(
            model_name='gearratiocalculation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='gearratiocalculation',
            name='eighth_gear',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearratiocalculation',
            name='front_torque_split',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gearratiocalculation',
            name='ninth_gear',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='fifth_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='final_drive',
            field=models.DecimalField(decimal_places=3, help_text='Final drive ratio', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='first_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='fourth_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='gear_spacing_strategy',
            field=models.CharField(choices=[('LINEAR', 'Linear Spacing'), ('GEOMETRIC', 'Geometric Progression'), ('CUSTOM', 'Custom Tuned')], default='GEOMETRIC', help_text='Strategy for spacing gear ratios', max_length=20),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='min_corner_gear',
            field=models.IntegerField(help_text='Minimum gear used in corners', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='min_corner_speed_mph',
            field=models.FloatField(help_text='Minimum corner entry speed', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='num_gears',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(4, message='Minimum 4 gears'), django.core.validators.MaxValueValidator(9, message='Maximum 9 gears')]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='second_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='seventh_gear',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='sixth_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='third_gear',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='tire_diameter_inches',
            field=models.FloatField(help_text='Tire diameter in inches', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gearratiocalculation',
            name='top_speed_mph',
            field=models.FloatField(help_text='Target top speed in miles per hour', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
