# Generated by Django 5.1.7 on 2025-03-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0009_remove_gearratiocalculation_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powercurvepoint',
            name='calculation',
        ),
        migrations.DeleteModel(
            name='GearRatioCalculation',
        ),
        migrations.DeleteModel(
            name='PowerCurvePoint',
        ),
    ]
