# Generated by Django 5.1.7 on 2025-03-24 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehicle_car_type_vehicle_drivetrain'),
        ('spring_calc', '0010_remove_powercurvepoint_calculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_speed_mph', models.IntegerField(default=180, help_text='Top speed on straight in mph')),
                ('min_corner_speed_mph', models.IntegerField(default=60, help_text='Minimum corner speed in mph')),
                ('tire_diameter_inches', models.FloatField(default=25.0, help_text='Tire diameter in inches')),
                ('performance_points', models.IntegerField(blank=True, help_text='Performance Points (PP)', null=True)),
                ('max_rpm', models.IntegerField(default=8000, help_text='Maximum engine RPM')),
                ('power_hp', models.IntegerField(default=500, help_text='Engine power in HP')),
                ('torque_kgfm', models.FloatField(default=50.0, help_text='Engine torque in kg-fm')),
                ('redline_rpm', models.IntegerField(default=7500, help_text='Engine redline RPM')),
                ('num_gears', models.IntegerField(default=6, help_text='Number of gears')),
                ('final_drive', models.FloatField(default=3.7, help_text='Final drive ratio')),
                ('gear_ratios', models.JSONField(blank=True, default=dict, null=True)),
                ('top_speed_calculated', models.FloatField(blank=True, help_text='Calculated top speed in mph', null=True)),
                ('acceleration_estimate', models.FloatField(blank=True, help_text='Estimated 0-60 time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle')),
            ],
        ),
    ]
