# Generated by Django 5.1.7 on 2025-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0011_gearcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearcalculation',
            name='performance_points',
        ),
        migrations.RemoveField(
            model_name='gearcalculation',
            name='redline_rpm',
        ),
        migrations.AddField(
            model_name='gearcalculation',
            name='max_power_rpm',
            field=models.IntegerField(default=6500, help_text='RPM at maximum power'),
        ),
        migrations.AddField(
            model_name='gearcalculation',
            name='min_corner_gear',
            field=models.IntegerField(default=1, help_text='Minimum corner gear'),
        ),
        migrations.AddField(
            model_name='gearcalculation',
            name='min_rpm',
            field=models.IntegerField(default=1000, help_text='Minimum engine RPM'),
        ),
        migrations.AlterField(
            model_name='gearcalculation',
            name='tire_diameter_inches',
            field=models.FloatField(blank=True, help_text='Tire diameter in inches', null=True),
        ),
    ]
