# Generated by Django 5.1.7 on 2025-03-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehicle_car_type_vehicle_drivetrain'),
        ('spring_calc', '0012_remove_gearcalculation_performance_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Setup name', max_length=100)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('gear_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spring_calc.gearcalculation')),
                ('spring_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spring_calc.springcalculation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicle')),
            ],
        ),
    ]
