# Generated by Django 5.1.7 on 2025-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0013_savedsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearcalculation',
            name='torque_curve',
            field=models.JSONField(blank=True, default=list, help_text='Torque curve data as array of [rpm, torque] pairs', null=True),
        ),
    ]
