# Generated by Django 5.1.7 on 2025-04-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring_calc', '0014_gearcalculation_torque_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springcalculation',
            name='performance_points',
            field=models.FloatField(blank=True, help_text='Performance Points (PP)', null=True),
        ),
    ]
